my_app/community/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, ValidationError

from my_app.models import Area, Profile
from my_app import photos


class ProfileForm(FlaskForm):
    """ Class for the profile form """
    username = StringField(label='Username', validators=[DataRequired(message='Username is required')])
    bio = TextAreaField(label='Bio', description='Write something about yourself')
    photo = FileField('Profile picture', validators=[FileAllowed(photos, 'Images only!')])
    area = QuerySelectField(label='Your location', query_factory=lambda: Area.query.all(),
                            get_label='area', allow_blank=True)

    def validate_username(self, username):
        profile = Profile.query.filter_by(username=username.data).first()
        if profile is not None:
            raise ValidationError('Username already exists, please choose another username')

my_app/community/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user

from my_app import photos, db
from my_app.community.forms import ProfileForm
from my_app.models import Profile, User

community_bp = Blueprint('community', __name__, url_prefix='/community')


@community_bp.route('/')
@login_required
def index():
    return render_template('community.html', title="Community")


@community_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    profile = Profile.query.join(User).filter(User.id == current_user.id).first()
    if profile:
        return redirect(url_for('community.update_profile'))
    else:
        return redirect(url_for('community.create_profile'))


@community_bp.route('/create_profile', methods=['GET', 'POST'])
@login_required
def create_profile():
    form = ProfileForm()
    if request.method == 'POST' and form.validate_on_submit():
        # Set the filename for the photo to None, this is the default if the user hasn't chosen to add a profile photo
        filename = None
        # Check if the form contains a photo (photo is the field name we used in the ProfileForm class)
        if 'photo' in request.files:
            # As long as the filename isn't empty then save the photo
            if request.files['photo'].filename != '':
                # Save the photo using the global variable photos to get the location to save to
                filename = photos.save(request.files['photo'])
        # Build a new profile to be added to the database based on the fields in the form
        # Note that the area.data is an object and we want to access the area property of the object
        p = Profile(area=form.area.data.area, username=form.username.data, photo=filename, bio=form.bio.data,
                    user_id=current_user.id)
        db.session.add(p)  # Add the new Profile to the database session
        db.session.commit()  # Saves the new Profile to the database
        return redirect(url_for('community.display_profiles', username=p.username))
    return render_template('profile.html', form=form)


@community_bp.route('/update_profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    profile = Profile.query.join(User).filter_by(id=current_user.id).first()
    form = ProfileForm(obj=profile)
    if request.method == 'POST' and form.validate_on_submit():
        if 'photo' in request.files:
            filename = photos.save(request.files['photo'])
            profile.photo = filename
        profile.area = form.area.data.area
        profile.bio = form.bio.data
        profile.username = form.username.data
        db.session.commit()
        return redirect(url_for('community.display_profiles', username=profile.username))
    return render_template('profile.html', form=form)


@community_bp.route('/display_profiles', methods=['POST', 'GET'])
@community_bp.route('/display_profiles/<username>/', methods=['POST', 'GET'])
@login_required
def display_profiles(username=None):
    results = None
    if username is None:
        if request.method == 'POST':
            term = request.form['search_term']
            if term == "":
                flash("Enter a name to search for")
                return redirect(url_for("community.index"))
            results = Profile.query.filter(Profile.username.contains(term)).all()
    else:
        results = Profile.query.filter_by(username=username).all()
    if not results:
        flash("Username not found.")
        return redirect(url_for("community.index"))
    urls = []
    for result in results:
        url = photos.url(result.photo)
        urls.append(url)
    return render_template('display_profile.html', profiles=zip(results, urls))

my_app/main/routes.py
from flask import Blueprint, render_template
from flask_login import current_user

main_bp = Blueprint('main', __name__)


@main_bp.route('/', defaults={'name': 'Anonymous'})
@main_bp.route('/<name>')
def index(name):
    if not current_user.is_anonymous:
        name = current_user.firstname
    return render_template('index.html', title='Home page', name=name)

my_app/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group">
        <dt>{{ field.label }}
        <dd>{{ field(**kwargs)|safe }}
            {% if field.errors %}
                <ul class=errors>
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </dd>
    </div>
{% endmacro %}

my_app/templates/community.html
{% extends 'layout.html' %}
{% block content %}
    <h1>{{ title }}</h1>
    <p>This is the community page.</p>
{% endblock %}

my_app/templates/display_profile.html
{% extends 'layout.html' %}
{% set title = 'Profile Display' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    {% for result, url in profiles %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{ url }}" alt="User profile photo">
            <div class="card-body">
                <h5 class="card-title">{{ result.username }}</h5>
                <h6>{{ result.area }}</h6>
                <p class="card-text">{{ result.bio }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

my_app/templates/index.html
{% extends 'layout.html' %}
{% block content %}
    <h1>{{ title }}</h1>
    <p>Welcome {{ name }}</p>
    <p>This is the my_app home page.</p>
{% endblock %}

my_app/templates/login.html
{% extends 'layout.html' %}
{% set title = 'Login' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <form method="POST" action="{{ url_for('auth.login') }}">
                {{ form.csrf_token }}
                <dl>
                    {{ render_field(form.email, class="form-control") }}
                    {{ render_field(form.password, class="form-control") }}
                    {{ render_field(form.remember, class="form-check-input") }}
                </dl>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

my_app/templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <img alt="recycle logo" style="margin-right:10px" class=img-thumbnail width=50px
             src="{{ url_for('static', filename='img/logo.png') }}">
        <a class="navbar-brand" href="{{ url_for("main.index") }}">Reduce, recycle, reuse!</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("main.index") }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("community.index") }}">Community</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/dash_app/">Dash app</a>
                </li>
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.login") }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a id="signup-nav" class="nav-link" href="{{ url_for("auth.signup") }}">Sign up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("community.profile") }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">Logout</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{{ url_for("community.display_profiles") }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                       name="search_term">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

my_app/templates/profile.html
{% extends 'layout.html' %}
{% set title = 'Profile' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.username, class="form-control") }}
            {{ render_field(form.bio, class="form-control") }}
            {{ render_field(form.area, class="form-control") }}
            {{ render_field(form.photo, class="custom-file", id="input_file") }}

        </dl>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

my_app/templates/signup.html
{% extends 'layout.html' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <br>
    <div class="card" style="width: 25rem;">
        <div class="card-body">
            <form method="POST" action="{{ url_for('auth.signup') }}" novalidate>
                {{ form.csrf_token }}
                <dl>
                    {{ render_field(form.first_name, class="form-control") }}
                    {{ render_field(form.last_name, class="form-control") }}
                    {{ render_field(form.email, class="form-control") }}
                    {{ render_field(form.password, class="form-control") }}
                    {{ render_field(form.password_repeat, class="form-control") }}
                </dl>
                <button id="submit" type="submit" class="btn btn-primary">Sign up</button>
            </form>
        </div>
    </div>
{% endblock %}